/*
Given a string s, check if it can be constructed by taking a substring of it and appending multiple copies of the substring together.

Example 1:
Input: s = "abab"
Output: true
Explanation: It is the substring "ab" twice.

Example 2:
Input: s = "aba"
Output: false

Example 3:
Input: s = "abcabcabcabc"
Output: true
Explanation: It is the substring "abc" four times or the substring "abcabc" twice.

Constraints:

    1 <= s.length <= 104
    s consists of lowercase English letters.

*/

var repeatedSubstringPattern = function (s) {
    let fullStr = "";
    for (let i = 2; i <= s.length; i++) {
        fullStr = "";
        const divide = Math.floor(s.length / i);
        const substr = s.substring(0, divide);

        for (let j = 1; j <= i; j++) {
            fullStr = fullStr + substr;
        }

        if (fullStr === s) {
            return true;
        }
    }
    return false;
};

var repeatedSubstringPattern = function (s) {
    const doubled = s + s;
    const sub = doubled.slice(1, -1);
    return sub.includes(s);
};

console.log(repeatedSubstringPattern("ababab"));
console.log("--------------");
console.log(repeatedSubstringPattern("aba"));
console.log("--------------");
console.log(repeatedSubstringPattern("abcabcabcabc"));
console.log("--------------");

console.log(
    repeatedSubstringPattern(
        "dcddrzglxknrqhipqrivdgixxtutzfwejbidaqoyddrtkzlaqvxubhrablwcssgctqfvhvvmanfkmsmfomzrtsuugqwyifcdvhyeeuqejyqvsdairbakuuhamfaukdzimxotthxehqczveimgkwagfcslcoxhnfumwnidmmkcqlxvtlbfidlnffajtyridnxbcheovotmaqhveidmnobswcdrawcfjzhlincdevpgnydrggftxhntltknpmubndmvrobvlsbzreqznwvkfidsdpftezwtdirwzsrmkulbaedncyzjicbmughyfdrknigoczbnvoqwsvlwtlfcpgqjmxjucbgplneomhdivvgqrtmkgsoyyehnbrhfunvfcbvriybfujvlcixlcmjaqqpujyzdowlqzghjfkpbtmoyuljwzszskoounnzbmmtltdvanmbhyrfteoreiswshkowzqzncszxvwxjiasgtxbynvcvnapwmeulutzyoawlwvweyokrnorajtxwvnvhrpvnjwnxwjkuhhahvmajasljljijwdqpsnedjrchdndmudtpqtaqlmczxkitpakjoonzfpjkemwyqpqilsywecxbohwdignywczetioyvlyncqvnjvmpajtotpubyjbulayglneiafxcvsqepewrnpgggcjelmbypbeaqliqqhvlzlsqpqiefqnlsysfntdcwhenuodkvyywlsociwjnoyaiysnlnqnkatxuhchcdfaqxpvhneuccwkcraoeqdqsxppgswjxdlnaaijoodqsbcvscjxvmpplfesxcdwfojhpuqdivvdxzypcjozxeojjtbivggdupkllbqwwlzvnzlpibqffeqqztavzgywykhjlyhklifyhsprufzbmrslluimbiiztqkgquqbcycmqtfkbemnygyjchvdreekwrronjpphtdynjkopydnebyjkwmcctoymhmzrdqyzuwofjewhhmokkxxglbiepiqxwpqcgodcnrhwvffertoeqnmcovigfbfesviallcaelwbrcfkxvoojbsxyaffbkluftuteztkmslfwqqtmgjxhbwhecphmaduuapazillawtwpjsdpbazdwijaxqpyujswauvifijcbhrmzwebwfgunpvlhkldvfzvzwdfhojkyczxydauiioxzlkhvvmqamnakrfrhqefsddqifmqocpnoawlvjcyxpyhifbqxhxpkchuivkyxblnbizztdxqsxzdeavbjsqvvzpfuzdtdojeyidrlchfzhkfjfgtayqvxgcthfpkvypuiunvzvaaengpumkulbrkhtgoavzwvqsdmfyncaoinuyiikctlwgupmlqhmoccghqlfeohuyvowfyhjuufarxocpvodzsjgiwnomuilryhwxqgtnntekhgzeuefonnwkanywxjowtmvluoyijcuskwwgabuoqtaqgyodkcbdpyojmntxropeknkkqhagacyidnnnprqepgqevjbnxttjgfwxmwdozcyepmrgfhnundyjmcymvtxbytalqebriavxoodtvqnkvovksvwnovqnprahvbyfbvcpjhkgaysxoqhgnfvcblrqctxzuxeyuipdsalsafroxzwlerphcgxhzwivtntnxlspnfjnlbdkczvgqkouqnbrkknfzityvnqitzvgcyqezmnpydkrsniczxiyidzdspolqjttkmzjaobyrnpkaaoazyahdznwobjhmdaypbkpqlnjyftafkagkdoocdktgtasyctnddcvosfozaogkrmvuclyfvrlqtgpvzebchwsbbgacwionulhxwgctzqktwbqvfrzoqrrrztvvbmlwxstwaxpcnbxlcngkhhyxaqqzlovnagjzacvdznhpoeattjfcqdbrvsshgpwixfhajffksmzisadlliqboruljpureqbcxlcgqhrkvqunsaadiqhyidmtsgnxzobwbfdrowdjmayhaymiptjzzvurdhqeytbzygtocwxqwvxwukhlfsmgpgyuoqzmmcnkigzkdycbwaasmjdtdpasxamlslzennrxtsjyqmcmoeganjvsavkyxylqmnwbanzvfiwywymketmreijhfvhftsxfhthhjifqqbonbdzfymycujjbgsgzldhszqciyjyqmpfnsfuqruunfgolyvmlavezlihjtiafxfupmohdkdqpjhcieqtemzexjnjcvlhssbjfrsidwbuhiwpmnlsbkyawmjyjuieplpudieggfdnpzfdoqwrcwsyibzuyhynspjxxngfvjtmiaqzqoqskktvmspmbpbtekrexzjuiehsezrwnkrzukuielufavahhtlhswbadktjjmgyyxytjudpgauivupdqamiznjcaellqrmpqmkbgnqmnmxljmqznchmrsqrwbdnvreldopjbfyrsvcdhscwwjkncafycknzbrkefbpjjpadkcguwiqsrdhvfmwjyjibdthiwxtfmtizxotvwlpqqxlwlhfktonwjvgfualgvthtkcqgogwgdkcoriamyoihlpofpznkvvffxwnnemuhwwxpgacgoknbbegsdtfaokhoixbmjvvfuvwcvyjllymocshinmicwsqhptvaprhlmdnjewwpvidxcmfpyqtxklebfzdwskhgnwrtvnksvorzczrbrmybyeeffhdarmggiaafnkxlapkdodgfqgiommvrtytmkauuauaphzajoloeoujgarwmfrgarzmdbjydfatmztyqgmuxjedlxcaftgflhuqldooiqjxqfvinjcksgqeguglnosavorgrhxcaizsnwabfcnalfgrzmepaypxniegsdisljkzhkcpmprxxxqwjwllxdiklosdrdxfohgwringzefwbytmwgxtjhdxwycpbawphcnbmajmeokhoftlmsexakuyixplxmagoojdospvjbcxhwivqpsqbpqjogwnswtimdlbxcwgeaenwokndefetwpjenwwksgwxszuwxbcyhpwvzlbethzpzjvmhtwzzvwtwrqwuswbiuwjgxpzhrqgalsherjfofzkypisjgttbsdhruiylaennzxtqgyelxqkozeyfargswplrzmezqsmppfhvglifcuwdzukbnrtmigfksjjldycufkplxatzupevlpwyirmsyrcsdodgmgbtssfpsarppvkakhasannaeptjdyqpgtlynqogshxhchhpqhjrwwtdmmmplehtxsslkitcpqlrzsiqbsjyoedarpseubxttrgfbbhqtsktmslpkwpbasbtkvxgwxbpqiwslfkfzuylpldbhschngbxbadyzepqomkatuhtrfggsjjzemgrsjovmrtlxldmzposkvldcsluduthibycnmyzftmfestfhhytelwgfjcjevqoyrrnfpmnkzsprluasuuygselcgwidpwdgprnefargsgzfcazzuxfodsqjraogxuomnbtsekzwsycwabvwzclcxdoqeewbampnpkgtwhqqhupixkeyprdovrezxccyotnfevzccrtmliuiuahlskbndhocjqczlqfpneusvneixastabfulijqqxvzpxbbpisfmoxjbbtabludnbyajjtzhobyncbfkwkykjjomconpkscnsdxcyylmzjbdnipjuptdahpcyeskxwyrbvtzvenvqrafzsouhjzirpmrvgbudzmgwhgsovpemplohzirijbbynswuwqzxcfuknmyjbexsplcqvvafwcfjwbfuugswmmibaimdokxfxzxvuyasahcyljtfqldcxofzwscnezsbbqwxqyqqisotdhatsdxrrdsqvudbwxcxpbufbkxlemgivgbqmbjdecvbyycuygrpjmvlyuydifnelqwzrfdvjyyizcczjwosklfigenojauwtqwkybijbgrajwbusqmcbukhyayjashvlfglgqukwmmhiodcesehmqrmqpvtjeoumufukaejorsyhwaloeuculolalgmpugbrowdqcoevhecfenvkixevnrwyzipuqtngrqwtfcpogrtmhqwrpdmcwkawurslkftdvqzauqqbjjpqbmjqpwsniujdmbqygjeebdgwtxzcgoviceatcthlnqqbugccrggtlnpgkqksefchmdaqyhdnatpwbtytbhomudsgtcazkdgyijogsuvspkqrfrmgyauufocatczdhidpttxlntgdfwwnnktnmqhrejtxmucveflxzkjmdrrlppyfztsnjagolznzwqvaviywsjlycelrujwverlotreerrenjbphjpddaqdcvowrzuoelzueryjkrpzdsokdgpggimldahwcbkinkctdccnvtmylckoicxrkjcpljlnmxvbhzvmbzzztnzgskvcoutadxpoicevzbwjbtvetxdmmdseppjfjcfocwfkylfzmeipzgwsdzgrebwvshaelhsndxydifdxllmltifwkooqpmohtqngygudfshqzknlvbyrmfnwtdoircsmtfttnnwthdjinyvlztclbrjuxadocxdxewsslpluuwekuaxtvbhwssrrswixvlwzjprwgesccwmwyjsumbsftlyohglerhecyxygeqjgpvfnhzjtceavpzjzhwdbgjdehelnuwvlrababkwdowbexmffjigrsjvbpiqmglxaoyaplwtzvwfuimzrvhkptgsiqiuxtszhszzdyufvqmpyzpswyclrkfadnwciqbqjcroaltvbglbfcvbcaoumtwpisrqjuiuxzizkcvnkirrmmuooikbdgqlbkbmgmgdlodysancketytnmhxziahbninrwtdczqtcolecqoilmbbalyzvbhwqrlhofmsedlitzmvrcgeohfqsgqqhzmzqajghvbnaovdcddrzglxknrqhipqrivdgixxtutzfwejbidaqoyddrtkzlaqvxubhrablwcssgctqfvhvvmanfkmsmfomzrtsuugqwyifcdvhyeeuqejyqvsdairbakuuhamfaukdzimxotthxehqczveimgkwagfcslcoxhnfumwnidmmkcqlxvtlbfidlnffajtyridnxbcheovotmaqhveidmnobswcdrawcfjzhlincdevpgnydrggftxhntltknpmubndmvrobvlsbzreqznwvkfidsdpftezwtdirwzsrmkulbaedncyzjicbmughyfdrknigoczbnvoqwsvlwtlfcpgqjmxjucbgplneomhdivvgqrtmkgsoyyehnbrhfunvfcbvriybfujvlcixlcmjaqqpujyzdowlqzghjfkpbtmoyuljwzszskoounnzbmmtltdvanmbhyrfteoreiswshkowzqzncszxvwxjiasgtxbynvcvnapwmeulutzyoawlwvweyokrnorajtxwvnvhrpvnjwnxwjkuhhahvmajasljljijwdqpsnedjrchdndmudtpqtaqlmczxkitpakjoonzfpjkemwyqpqilsywecxbohwdignywczetioyvlyncqvnjvmpajtotpubyjbulayglneiafxcvsqepewrnpgggcjelmbypbeaqliqqhvlzlsqpqiefqnlsysfntdcwhenuodkvyywlsociwjnoyaiysnlnqnkatxuhchcdfaqxpvhneuccwkcraoeqdqsxppgswjxdlnaaijoodqsbcvscjxvmpplfesxcdwfojhpuqdivvdxzypcjozxeojjtbivggdupkllbqwwlzvnzlpibqffeqqztavzgywykhjlyhklifyhsprufzbmrslluimbiiztqkgquqbcycmqtfkbemnygyjchvdreekwrronjpphtdynjkopydnebyjkwmcctoymhmzrdqyzuwofjewhhmokkxxglbiepiqxwpqcgodcnrhwvffertoeqnmcovigfbfesviallcaelwbrcfkxvoojbsxyaffbkluftuteztkmslfwqqtmgjxhbwhecphmaduuapazillawtwpjsdpbazdwijaxqpyujswauvifijcbhrmzwebwfgunpvlhkldvfzvzwdfhojkyczxydauiioxzlkhvvmqamnakrfrhqefsddqifmqocpnoawlvjcyxpyhifbqxhxpkchuivkyxblnbizztdxqsxzdeavbjsqvvzpfuzdtdojeyidrlchfzhkfjfgtayqvxgcthfpkvypuiunvzvaaengpumkulbrkhtgoavzwvqsdmfyncaoinuyiikctlwgupmlqhmoccghqlfeohuyvowfyhjuufarxocpvodzsjgiwnomuilryhwxqgtnntekhgzeuefonnwkanywxjowtmvluoyijcuskwwgabuoqtaqgyodkcbdpyojmntxropeknkkqhagacyidnnnprqepgqevjbnxttjgfwxmwdozcyepmrgfhnundyjmcymvtxbytalqebriavxoodtvqnkvovksvwnovqnprahvbyfbvcpjhkgaysxoqhgnfvcblrqctxzuxeyuipdsalsafroxzwlerphcgxhzwivtntnxlspnfjnlbdkczvgqkouqnbrkknfzityvnqitzvgcyqezmnpydkrsniczxiyidzdspolqjttkmzjaobyrnpkaaoazyahdznwobjhmdaypbkpqlnjyftafkagkdoocdktgtasyctnddcvosfozaogkrmvuclyfvrlqtgpvzebchwsbbgacwionulhxwgctzqktwbqvfrzoqrrrztvvbmlwxstwaxpcnbxlcngkhhyxaqqzlovnagjzacvdznhpoeattjfcqdbrvsshgpwixfhajffksmzisadlliqboruljpureqbcxlcgqhrkvqunsaadiqhyidmtsgnxzobwbfdrowdjmayhaymiptjzzvurdhqeytbzygtocwxqwvxwukhlfsmgpgyuoqzmmcnkigzkdycbwaasmjdtdpasxamlslzennrxtsjyqmcmoeganjvsavkyxylqmnwbanzvfiwywymketmreijhfvhftsxfhthhjifqqbonbdzfymycujjbgsgzldhszqciyjyqmpfnsfuqruunfgolyvmlavezlihjtiafxfupmohdkdqpjhcieqtemzexjnjcvlhssbjfrsidwbuhiwpmnlsbkyawmjyjuieplpudieggfdnpzfdoqwrcwsyibzuyhynspjxxngfvjtmiaqzqoqskktvmspmbpbtekrexzjuiehsezrwnkrzukuielufavahhtlhswbadktjjmgyyxytjudpgauivupdqamiznjcaellqrmpqmkbgnqmnmxljmqznchmrsqrwbdnvreldopjbfyrsvcdhscwwjkncafycknzbrkefbpjjpadkcguwiqsrdhvfmwjyjibdthiwxtfmtizxotvwlpqqxlwlhfktonwjvgfualgvthtkcqgogwgdkcoriamyoihlpofpznkvvffxwnnemuhwwxpgacgoknbbegsdtfaokhoixbmjvvfuvwcvyjllymocshinmicwsqhptvaprhlmdnjewwpvidxcmfpyqtxklebfzdwskhgnwrtvnksvorzczrbrmybyeeffhdarmggiaafnkxlapkdodgfqgiommvrtytmkauuauaphzajoloeoujgarwmfrgarzmdbjydfatmztyqgmuxjedlxcaftgflhuqldooiqjxqfvinjcksgqeguglnosavorgrhxcaizsnwabfcnalfgrzmepaypxniegsdisljkzhkcpmprxxxqwjwllxdiklosdrdxfohgwringzefwbytmwgxtjhdxwycpbawphcnbmajmeokhoftlmsexakuyixplxmagoojdospvjbcxhwivqpsqbpqjogwnswtimdlbxcwgeaenwokndefetwpjenwwksgwxszuwxbcyhpwvzlbethzpzjvmhtwzzvwtwrqwuswbiuwjgxpzhrqgalsherjfofzkypisjgttbsdhruiylaennzxtqgyelxqkozeyfargswplrzmezqsmppfhvglifcuwdzukbnrtmigfksjjldycufkplxatzupevlpwyirmsyrcsdodgmgbtssfpsarppvkakhasannaeptjdyqpgtlynqogshxhchhpqhjrwwtdmmmplehtxsslkitcpqlrzsiqbsjyoedarpseubxttrgfbbhqtsktmslpkwpbasbtkvxgwxbpqiwslfkfzuylpldbhschngbxbadyzepqomkatuhtrfggsjjzemgrsjovmrtlxldmzposkvldcsluduthibycnmyzftmfestfhhytelwgfjcjevqoyrrnfpmnkzsprluasuuygselcgwidpwdgprnefargsgzfcazzuxfodsqjraogxuomnbtsekzwsycwabvwzclcxdoqeewbampnpkgtwhqqhupixkeyprdovrezxccyotnfevzccrtmliuiuahlskbndhocjqczlqfpneusvneixastabfulijqqxvzpxbbpisfmoxjbbtabludnbyajjtzhobyncbfkwkykjjomconpkscnsdxcyylmzjbdnipjuptdahpcyeskxwyrbvtzvenvqrafzsouhjzirpmrvgbudzmgwhgsovpemplohzirijbbynswuwqzxcfuknmyjbexsplcqvvafwcfjwbfuugswmmibaimdokxfxzxvuyasahcyljtfqldcxofzwscnezsbbqwxqyqqisotdhatsdxrrdsqvudbwxcxpbufbkxlemgivgbqmbjdecvbyycuygrpjmvlyuydifnelqwzrfdvjyyizcczjwosklfigenojauwtqwkybijbgrajwbusqmcbukhyayjashvlfglgqukwmmhiodcesehmqrmqpvtjeoumufukaejorsyhwaloeuculolalgmpugbrowdqcoevhecfenvkixevnrwyzipuqtngrqwtfcpogrtmhqwrpdmcwkawurslkftdvqzauqqbjjpqbmjqpwsniujdmbqygjeebdgwtxzcgoviceatcthlnqqbugccrggtlnpgkqksefchmdaqyhdnatpwbtytbhomudsgtcazkdgyijogsuvspkqrfrmgyauufocatczdhidpttxlntgdfwwnnktnmqhrejtxmucveflxzkjmdrrlppyfztsnjagolznzwqvaviywsjlycelrujwverlotreerrenjbphjpddaqdcvowrzuoelzueryjkrpzdsokdgpggimldahwcbkinkctdccnvtmylckoicxrkjcpljlnmxvbhzvmbzzztnzgskvcoutadxpoicevzbwjbtvetxdmmdseppjfjcfocwfkylfzmeipzgwsdzgrebwvshaelhsndxydifdxllmltifwkooqpmohtqngygudfshqzknlvbyrmfnwtdoircsmtfttnnwthdjinyvlztclbrjuxadocxdxewsslpluuwekuaxtvbhwssrrswixvlwzjprwgesccwmwyjsumbsftlyohglerhecyxygeqjgpvfnhzjtceavpzjzhwdbgjdehelnuwvlrababkwdowbexmffjigrsjvbpiqmglxaoyaplwtzvwfuimzrvhkptgsiqiuxtszhszzdyufvqmpyzpswyclrkfadnwciqbqjcroaltvbglbfcvbcaoumtwpisrqjuiuxzizkcvnkirrmmuooikbdgqlbkbmgmgdlodysancketytnmhxziahbninrwtdczqtcolecqoilmbbalyzvbhwqrlhofmsedlitzmvrcgeohfqsgqqhzmzqajghvbnaov"
    )
);

console.log("--------------");
console.log(repeatedSubstringPattern("abcabcabc"));

console.log("--------------");
console.log(repeatedSubstringPattern("ababababab"));
